Update Concise-Guide-for-Evaluating-Open-Source-Software.md
ossf/wg-best-practices-os-developers pull request #156
Opened 2023-05-26 06:45 UTC by carolinacanales

Previous link was not working, added the right one: https://github.com/ossf/oss-vulnerability-guide/blob/main/maintainer-guide.md

2023-05-26 07:16 UTC, gkunz approved these changes
LGTM

2023-05-26 19:10 UTC, david-a-wheeler commented
Can we modify this URL so the reader doesn't need to see all the GitHub preamble?

It looks like the trick of adding "#readme" isn't working.  But using this URL instead means that user won't need to see a lot of unnecessary header:

> https://github.com/ossf/oss-vulnerability-guide/blob/main/maintainer-guide.md#guide-to-implementing-a-coordinated-vulnerability-disclosure-process-for-open-source-projects

2023-06-05 19:45 UTC, gkunz commented
I see your point - at the same time, adding the reference to the heading increases the chances of breaking the link due to any sort of renaming of the heading... And renaming caused this issue in the first place.

2023-06-08 14:33 UTC, david-a-wheeler commented
> adding the reference to the heading increases the chances of breaking the link due to any sort of renaming of the heading... And renaming caused this issue in the first place.

If the anchor name link changes (the material after '#'), the user will still get to the page, just to the top instead of the intended header. That still seems like a win, you're "no worse off".

I think the best practices WG will soonish have a "better publishing process". If it seems useful, we can replicate it for any other group that desires it.

2023-06-12 11:42 UTC, gkunz requested changes

2023-06-12 11:42 UTC, gkunz commented on docs/Concise-Guide-for-Evaluating-Open-Source-Software.md
> +6. **Are there instructions on how to report vulnerabilities?** See the [Guide to implementing a coordinated vulnerability disclosure process for open source projects](https://github.com/ossf/oss-vul
@carolinacanales:

```suggestion
6. **Are there instructions on how to report vulnerabilities?** See the [Guide to implementing a coordinated vulnerability disclosure process for open source projects](https://github.com/ossf/oss-vulnerability-guide/blob/main/maintainer-guide.md#guide-to-implementing-a-coordinated-vulnerability-disclosure-process-for-open-source-projects) for guidance to OSS projects.
```

2023-06-14 12:03 UTC, merged