Flag usage recommendations
ossf/wg-best-practices-os-developers pull request #165
Opened 2023-06-07 11:45 UTC by thomasnyman

In PR https://github.com/ossf/wg-best-practices-os-developers/pull/132#issuecomment-1505292993 @david-a-wheeler noted that we need to note somewhere that the option flags are order-sensitive. Another feedback from the C/C++ Compiler BP Guide calls was to add the recommendation to to explicitly enable hardening flag in a projects build system rather then relying on flags configured in the local GCC profile. This PR adds text to address these concerns.

2023-06-07 14:14 UTC, thomasnyman commented
Updated PR with rebase with respect to main after renaming files

2023-06-21 13:39 UTC, thomasnyman commented on docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
> +You can typically find the default flags used by GCC on your system by examining the output of the `gcc -v` command. Examining the `Configured with:` section, in the `gcc -v` output, can be useful fo
Should include the corresponding flag for Clang (and possible the Microsoft compiler?)

Possible also the relevant variant for debugging issues with macros (`gcc -O2 -dM -E - < /dev/null`)

2023-08-02 11:53 UTC, thomasnyman commented
Minor further tweaks to avoid referring to only GCC.

2023-08-03 15:37 UTC, gkunz requested changes
generally looks good to me - except for the footnote syntax fix.

2023-08-03 15:40 UTC, gkunz commented on docs/Compiler-Hardening-Guides/Compiler-Options-Hardening-Guide-for-C-and-C++.md
> +[^ubuntu-hardening]: Ubuntu, [Ubuntu Security Features](https://wiki.ubuntu.com/Security/Features), Ubuntu Wiki
Based on #209:

```suggestion
[^debian-hardening]: Software in the Public Interest, [Hardening in Debian](https://wiki.debian.org/Hardening), Debian Wiki

[^gentoo-hardening]: Gentoo Foundation, [Hardening in Gentoo](https://wiki.gentoo.org/wiki/Hardened/Toolchain), Gentoo Wiki

[^fedora-hardening]: Red Hat, [Using RPM build flags in Fedora](https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/buildflags.md), Fedora Package Sources (`redhat-rpm-config`)

[^opensuse-hardening]: SUSE, [openSUSE Security Features](https://en.opensuse.org/openSUSE:Security_Features), openSUSE Wiki

[^ubuntu-hardening]: Ubuntu, [Ubuntu Security Features](https://wiki.ubuntu.com/Security/Features), Ubuntu Wiki
```

2023-08-03 16:48 UTC, thomasnyman commented
Squashed requested changes to original commit.

2023-08-03 16:48 UTC, merged

2023-08-03 16:49 UTC, thomasnyman commented
Merged as per discussion in [C/C++ Compiler Guide BP call 2023-08-02](https://docs.google.com/document/d/1UClGUnOSkOH_wab6Lx43KUdkaK37L8sbWJ_GPZvc1YY/edit#bookmark=id.82homkohrlln).