Add secret scanning to SCM guide, fixes #488
ossf/wg-best-practices-os-developers pull request #489
Opened 2024-05-14 21:20 UTC by david-a-wheeler

2024-05-16 19:53 UTC, david-a-wheeler commented
@SecurityCRob - comments?

I did *not* try to edit `best-practices.yml`. I'm not sure what that yml file is doing. Is that the source & the README is generated? I don't see any code to do the generation. If the .yml file is generated from the README, then please run that tool. If they're edited simultaneously, well, yuck :-(. In any case, there should be a clear document *somewhere* what their relationship is.

2024-05-16 23:44 UTC, ctcpip requested changes
this is great!  looks good, just some minor corrections, and a few consistency suggestions as well

2024-05-16 23:44 UTC, ctcpip commented on docs/SCM-BestPractices/README.md
> +* Secret Scanning Should be Enabled [<img src="https://user-images.githubusercontent.com/287526/230375178-2f1f8844-5609-4ef3-b9ac-141c20c43406.svg" alt="GitHub" height="20" width="20">](github/reposi
```suggestion
* Secret Scanning Should be Enabled [<img src="https://user-images.githubusercontent.com/287526/230375178-2f1f8844-5609-4ef3-b9ac-141c20c43406.svg" alt="GitHub" height="20" width="20">](github/repository/secret_scanning.md) [GitHub](github/repository/secret_scanning.md)
```

2024-05-16 23:44 UTC, ctcpip commented on docs/SCM-BestPractices/github/repository/secret_scanning.md
> +secrets (and creates and alert if that it overridden).
```suggestion
secrets (and creates an alert if that is overridden).
```

2024-05-16 23:44 UTC, ctcpip commented on docs/SCM-BestPractices/github/repository/secret_scanning.md
> +This is such a common kind of vulnerability that it is identified as
```suggestion
This is such a common type of vulnerability that it is identified as
```

2024-05-16 23:44 UTC, ctcpip commented on docs/SCM-BestPractices/github/repository/secret_scanning.md
> +3. Enter "Security" section of the sidebar, click Code security and analysis.
```suggestion
3. Enter "Security" section of the sidebar, click "Code security and analysis".
```

2024-05-16 23:44 UTC, ctcpip commented on docs/SCM-BestPractices/github/repository/secret_scanning.md
> +3. Enter "Security" section of the sidebar, click Code security and analysis.
```suggestion
3. Enter "Security" section of the sidebar, click "Code security and analysis".
```

2024-05-16 23:44 UTC, ctcpip commented on docs/SCM-BestPractices/github/repository/secret_scanning.md
> +5. Under "Secret scanning", under "Push protection", click Enable.
```suggestion
5. Under "Secret scanning", under "Push protection", click "Enable".
```

2024-05-16 23:44 UTC, ctcpip commented on docs/SCM-BestPractices/gitlab/project/secret_scanning.md
> +This is such a common kind of vulnerability that it is identified as
```suggestion
This is such a common type of vulnerability that it is identified as
```

2024-05-21 12:51 UTC, SecurityCRob approved these changes
I like the addition.  If we could get Chris' open comment resolved I think we can move this forward

2024-05-21 12:52 UTC, SecurityCRob commented
> @SecurityCRob - comments?
> 
> I did _not_ try to edit `best-practices.yml`. I'm not sure what that yml file is doing. Is that the source & the README is generated? I don't see any code to do the generation. If the .yml file is generated from the README, then please run that tool. If they're edited simultaneously, well, yuck :-(. In any case, there should be a clear document _somewhere_ what their relationship is.

I *think* Randall put that in place.  I'm also unsure how that works.  We should ask him to start.

2024-05-21 13:53 UTC, balteravishay commented
> > @SecurityCRob - comments?
> > I did _not_ try to edit `best-practices.yml`. I'm not sure what that yml file is doing. Is that the source & the README is generated? I don't see any code to do the generation. If the .yml file is generated from the README, then please run that tool. If they're edited simultaneously, well, yuck :-(. In any case, there should be a clear document _somewhere_ what their relationship is.
> 
> I _think_ Randall put that in place. I'm also unsure how that works. We should ask him to start.

I think that might relate to how the [Legitify](https://github.com/Legit-Labs/legitify) was used to produce these recommendations. maybe @noamd-legit  can comment on this and suggest how to add new ones?

2024-05-23 15:09 UTC, david-a-wheeler commented
In that case, I suggest removing the .yml file (in a separate pull request). We generally don't want generated files in the source repo.

@noamd-legit - would you mind creating that PR?

2024-05-30 09:08 UTC, noamd-legit commented
@david-a-wheeler 
Removed the file here: https://github.com/ossf/wg-best-practices-os-developers/pull/508

2024-11-05 15:35 UTC, balteravishay approved these changes

2024-11-05 15:36 UTC, merged