Doc2GitHub CWE-665
ossf/wg-best-practices-os-developers pull request #573
Opened 2024-08-08 13:20 UTC by myteron

As part of #531 , adding documentation to CWE-665

2024-08-14 10:25 UTC, BartyBoi1128 requested changes
Just left one comment for a missing "the" on line 22. Once this is added I will approve!

2024-08-14 10:25 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-665/README.md
> +In `SessionPool()` we spawn tasks and access control in following order:
This should probably say "in the following order" rather than "in following order"

2024-08-15 10:28 UTC, BartyBoi1128 approved these changes

2024-08-19 19:46 UTC, gkunz approved these changes
looks good to me.

2024-08-20 15:46 UTC, merged