CWE-755 and CWE-532
ossf/wg-best-practices-os-developers pull request #647
Opened 2024-10-09 10:27 UTC by BartyBoi1128

CWE-755 and CWE-532, Code scrub and Doc scrub changes

2024-10-09 16:16 UTC, myteron requested changes
the main readme.md is missing the entries for CWE-532 and CWE-755
https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/Secure-Coding-Guide-for-Python/readme.md

Add following SPDX headers to at least the top of the .py code examples. No need to quote SPDS in the README.md's

```
# SPDX-FileCopyrightText: OpenSSF project contributors
# SPDX-License-Identifier: MIT
```

2024-10-09 16:16 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/README.md
> +|[Pylint](https://pylint.pycqa.org/)|2023.10.1|[W1203:logging-fstring-interpolation](W1203:logging-fstring-interpolation)|Use lazy % formatting in logging functions|
References is also missing the 4 links in the introduction.

2024-10-09 16:16 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +""" Non-compliant Code Example """
Says """Non compliant .... expecting """ Compliant

2024-10-09 16:16 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +*[compliant01.py](compliant.py):*
the link in the brackets is missing `01`, should be (compliant01.py)

2024-10-09 16:16 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +## Risk Assessment
Remove Risk Assessment section

2024-10-16 16:18 UTC, myteron approved these changes

2024-10-23 10:50 UTC, s19110 requested changes

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/README.md
> +The `example01.py` solution uses a custom filter in Python's logging module to automatically mask sensitive data in the logs. While this is a good solution for central handling in large software proj
typo: variations

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/README.md
> +* CRITICAL
cosmetic: wrap with backticks:
`WARNING`
`ERROR`
`CRITICAL`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/README.md
> +The `noncompliant02.py` code has the log level set to DEBUG is causing the customer's address to appear in the console.
cosmetic: wrap with backticks: `DEBUG`, `INFO`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/compliant01.py
> +""" Compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/compliant02.py
> +""" Compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/example01.py
> +""" Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/noncompliant01.py
> +""" Non-compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-664/CWE-532/noncompliant02.py
> +""" Non-compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/compliant01.py
> +""" Non-compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/compliant02.py
> +""" Non-compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/noncompliant01.py
> +""" Non-compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/noncompliant02.py
> +""" Non-compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/noncompliant03.py
> +""" Non-compliant Code Example """
Add license comments on top of all the .py files. You don't need to put them in code chunks in readme files:
`# SPDX-FileCopyrightText: OpenSSF project contributors`
`# SPDX-License-Identifier: MIT`

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +## Non-Compliant Code Example (os.remove()/os.unlink())
cosmetic:
## Non-Compliant Code Example (`os.remove()`/`os.unlink()`)

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +|[CWE MITRE Class](https://cwe.mitre.org/)|[CWE-755](https://cwe.mitre.org/data/definitions/755.html), Improper Handling of Exceptional Conditions|
The reference to the CWE page is called "Class" here, but "Base" in CWE-532. I know it's the case for the original pages as well, but in my opinion, we should settle for one term to avoid confusion.

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +This code example demonstrates an attempt to read a non-existent file using the os module. The `read_file()` function opens a file and reads its content using `os.open()` and `os.read()`. If the file
cosmetic:  ... using the `os` module

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +## Compliant Solution (try/except blocks)
The (try/except blocks) part was not there originally. Personally, I prefer it this way. Just add backticks to make it consistent with my previous comment:

## Compliant Solution (`try/except` blocks)

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +## Non-Compliant Code Example (pathlib.Path.unlink())
cosmetic:

## Non-Compliant Code Example (`pathlib.Path.unlink()`)

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +The `pathlib.Path.unlink()` function has an optional parameter `missing_ok` that will suppress the `FileNotFoundError on file deletion`, if the parameter's value is `True` . However, without proper h
I believe that was a typo on the original page. It should be: `FileNotFoundError` on file deletion

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +## Compliant Solution (pathlib module)
cosmetic:
## Compliant Solution (`pathlib` module)

2024-10-23 10:50 UTC, s19110 commented on docs/Secure-Coding-Guide-for-Python/CWE-703/CWE-755/README.md
> +Since the `pathlib` module uses the same exceptions as the os module, error handling can be implemented in the same way.
cosmetic: ... as the `os` module...

2024-10-24 10:54 UTC, s19110 approved these changes

2024-10-24 10:57 UTC, myteron commented
got approval from 2 reviewers, merging in

2024-10-24 10:58 UTC, merged