Adding documentation to CWE-175 as part of #531
ossf/wg-best-practices-os-developers pull request #687
Opened 2024-10-31 15:04 UTC by s19110

Adding documentation to CWE-175 as part of #531

2024-11-02 14:32 UTC, myteron commented
The flow broke a bit since noncompliant01 got changed to example01.py we have  compliant03 now answering noncompliant02. Actually took me a while to figure that out when I was only verifying the code examples by them self.
The confluence code was never designed to have actual exploits or clear separation. So its kind of irritating now. 

Also compliant03 is not fixing in code but by asking the user to put in a different string seam's a bit of a cheat.

2024-11-06 11:44 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant03.py
> +# UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2e in position 1336: truncated data
After discussing this I believe its fastest to 
1) turn noncompliant02.py and compliant03.py into a example02.py and ask the reader to either put in either 12.345 or 12,345 to experience the issue.

2) Remove the exploit section / comment if there is no actual exploit to avoid confusion. Keep in mind that we will run static code analysis tools against the *compliant*.py examples. Be sure not to have any offensive code triggering a false positive.

2024-11-07 12:49 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +word = "Title"
Getting:
Constant name "word" doesn't conform to UPPER_CASE naming stylePylint[C0103:invalid-name](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/invalid-name.html)
Maybe just capitalise "word" variable to silence the linters?

2024-11-07 13:52 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant01.py
> +def get_date(date):
Getting the following on Flake:
expected 2 blank lines, found 1Flake8(E302)
Missing function or method docstringPylint[C0116:missing-function-docstring](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/missing-function-docstring.html)

2024-11-07 13:52 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant01.py
> +CURRENT_LOCALE = 'en_IE.utf8'
Getting the following on Flake:
expected 2 blank lines after class or function definition, found 1Flake8(E305)
(constant) CURRENT_LOCALE: Literal['en_IE.utf8']

2024-11-07 13:54 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant01.py
> +import datetime, locale
Getting these linters giving out about multiple imports on one line:
Multiple imports on one lineRuff[E401](https://docs.astral.sh/ruff/rules/multiple-imports-on-one-line)
Multiple imports on one line (datetime, locale)Pylint[C0410:multiple-imports](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/multiple-imports.html)
multiple imports on one lineFlake8(E401)
(module) datetime

2024-11-07 13:55 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant01.py
> +import datetime, locale
Linters giving out about linters on one line:
Multiple imports on one lineRuff[E401](https://docs.astral.sh/ruff/rules/multiple-imports-on-one-line)
Multiple imports on one line (datetime, locale)Pylint[C0410:multiple-imports](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/multiple-imports.html)
multiple imports on one lineFlake8(E401)
(module) datetime

2024-11-07 13:56 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant01.py
> +locale.setlocale(locale.LC_ALL, CURRENT_LOCALE)
Did you forget to initialise CURRENT_LOCALE in here?

2024-11-07 14:39 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +This simple code example does not set a locale and sets `ORIGINAL_NUMBER` for comparison to 12.345 (twelve point three-four-five). In Ireland, a comma is a thousands separator and a dot is a decimal
```suggestion
The `example03.py` code does not set a locale and sets `ORIGINAL_NUMBER` for comparison to 12.345 (twelve point three-four-five). In Ireland, a comma is a thousands separator and a dot is a decimal separator. In Germany these are reversed, so a comma is a decimal separator and a decimal is a thousands separator.
```

2024-11-07 14:39 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/example03.py
> +# SPDX-FileCopyrightText: OpenSSF project contributors
I believe that `example03.py` can be simplified and that we should keep CLI interaction to a minimum. Its enough to experience that a 12.345 with a German local results in 12345.0.

```suggestion
# SPDX-FileCopyrightText: OpenSSF project contributors
# SPDX-License-Identifier: MIT
""" Non-compliant Code Example """
import locale
 
def compare_number(number):
    input_number = locale.atof(input(f"Enter a number {number}: "))
    print(f"Locale is {locale.getlocale()}, you entered {input_number}.")
    print(f"Does the number {number} match {input_number}? {number == input_number}")

locale.setlocale(locale.LC_ALL, 'de_DE.utf8')
compare_number(12.345)

```

2024-11-07 14:58 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/example03.py
> +def compare_number(number):
Getting this from Flake:
expected 2 blank lines, found 1Flake8(E302)
Missing function or method docstringPylint[C0116:missing-function-docstring](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/missing-function-docstring.html)

2024-11-07 14:58 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/example03.py
> +print(f"Locale is {locale.getlocale()}")
Getting this from Flake:
expected 2 blank lines after class or function definition, found 1Flake8(E305)
(function) def print(
    *values: object,
    sep: str | None = " ",
    end: str | None = "\n",
    file: SupportsWrite[str] | None = None,
    flush: Literal[False] = False
) -> None
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.

2024-11-07 15:01 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant02.py
> +output  = io.BytesIO()
2 spaces here after "output"
Would change it myself but it won't let me!

2024-11-07 15:03 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant02.py
> +LOREM = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor
Got a lot of "Line too long" from Pylint... not sure if we care about this though:
Line too long (456/100)Pylint[C0301:line-too-long](https://pylint.readthedocs.io/en/latest/user_guide/messages/convention/line-too-long.html)
(constant) LOREM: Literal['Lorem ipsum dolor sit amet, consectetur adipiscing…']

Got that for lines 6,7,8 and 18

2024-11-07 15:04 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant02.py
> +LOREM = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor
Pylint giving out that lines 6, 7 and 8 are too long... not sure if we care though...

2024-11-07 15:04 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant02.py
> +output  = io.BytesIO()
2 spaces after "output" here

2024-11-11 14:46 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant03.py
compliant03 was renamed - solved

2024-11-21 11:13 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +word = "Title"
```suggestion
WORD = "Title"
```

2024-11-21 11:23 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant01.py
> +import datetime, locale
```suggestion
import datetime
import locale
```

2024-11-21 11:24 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant02.py
> +output  = io.BytesIO()
```suggestion
output = io.BytesIO()
```

2024-11-21 11:25 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/example03.py
> +ORIGINAL_NUMBER = 12.345  # This will read as 12,345 in German
```suggestion
ORIGINAL_NUMBER = 12.345  # This will read as 12,345 in German

```

2024-11-21 11:28 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant01.py
> +dt = datetime.datetime(2022, 3, 9, 12, 55, 35, 000000)
```suggestion
dt = datetime.datetime(2022, 3, 9, 12, 55, 35, 000000)

```

2024-11-21 11:29 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant01.py
> +#####################
```suggestion
#####################

```

2024-11-21 11:36 UTC, BartyBoi1128 requested changes
Left comments with suggestions, In "example03.py" I couldn't leave a suggested change on all the lines but essentially just wondering can we remove one "#" from the comments, just leave it at "#" rather than "##"

2024-11-21 12:03 UTC, s19110 commented
> Left comments with suggestions, In "example03.py" I couldn't leave a suggested change on all the lines but essentially just wondering can we remove one "#" from the comments, just leave it at "#" rather than "##"

Thank you for the suggestions, I have now merged all of them. As for the "##" in comments, I will change them to a singular "#" and indicate if they are supposed to be console output or something else.

2024-11-22 13:35 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant01.py
> +locale.setlocale(locale.LC_ALL, CURRENT_LOCALE)
This is resolved!

2024-11-22 13:35 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/example03.py
> +## Locale is ('English_Ireland', '1252')
Looks like this is resolved!

2024-11-22 13:36 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant02.py
> +LOREM = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco labor
Don't think we care here either, can be resolved

2024-11-27 12:12 UTC, myteron requested changes
`example01.py` code does not work. Rest is more or less cosmetic hope I got matching code between .py and .md

2024-11-27 12:12 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +The developer should be aware of the text encoding that is used for input data and output data in the program. The code example attempts to use UTF-16 LE encoding to read the LOREM `TextIOWrapper` st
```suggestion
The developer should be aware of the text encoding that is used for input data and output data in the program. The code example attempts to use `UTF-16 LE` encoding to read the LOREM `TextIOWrapper` stream which raises a `UnicodeDecodeError` exception as it was created with `UTF-8`.
```

2024-11-27 12:12 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +The correct text encoding, UTF-8 for the LOREM `TextIOWrapper` stream has been included in the program. Ensure the encoding of data is known and explicitly stated when parsing and creating data.
```suggestion
The correct text encoding, `UTF-8` for the LOREM `TextIOWrapper` stream has been included in the program. Ensure the encoding of data is known and explicitly stated when parsing and creating data.
```

2024-11-27 12:12 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +# 1337 characters in string
We are not exploiting anything here, comment is enough
```suggestion
# 1337 characters in string
print(f"{len(output.getvalue().decode('utf-8'))} characters in string")
```

2024-11-27 12:12 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/compliant02.py
> +# 1337 characters in string
Not exploiting anything, comment is enough:
```suggestion
# 1337 characters in string
print(f"{len(output.getvalue().decode('utf-8'))} characters in string")
```

2024-11-27 12:12 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/noncompliant02.py
> +# UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2e in position 1336: truncated data
Not an exploit, comment is enough
```suggestion
# Below outputs UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2e in position 1336: truncated data
print(f"{len(output.getvalue().decode('utf-16le'))} characters in string")
```

2024-11-27 12:12 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +# UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2e in position 1336: truncated data
Not an exploit, comment is enough
```suggestion
# Below outputs UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x2e in position 1336: truncated data
print(f"{len(output.getvalue().decode('utf-16le'))} characters in string")
```

2024-11-28 09:23 UTC, myteron approved these changes
All working

2024-11-28 09:23 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-175/README.md
> +
```suggestion
print(WORD.upper())
locale.setlocale(locale.LC_ALL, "tr_TR.utf8")
print(WORD.upper())
```

2024-11-28 15:19 UTC, BartyBoi1128 approved these changes

2024-11-28 15:43 UTC, merged