pySCG adding CWE-78 code and doc
ossf/wg-best-practices-os-developers pull request #689
Opened 2024-11-01 17:05 UTC by myteron

Adding CWE-78 as part of #531

2024-11-06 21:37 UTC, gkunz requested changes

2024-11-06 21:37 UTC, gkunz commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
> +Instead of listing files we have the `noncompliant01.py` code print the first line of `/etc/passwd` on Linux  or start `net user` under Windows.
```suggestion
Instead of listing files, the code in `noncompliant01.py` prints the first line of `/etc/passwd` on Linux or starts `net user` under Windows.
```

2024-11-06 21:37 UTC, gkunz commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
> +In `noncompliant02.py` we have the attacker create a file toast.sh file that contains the commands to run. The attacker also creates a folder named `. -exec bash toast.sh {} +` that will later become
```suggestion
In `noncompliant02.py` the attacker creates a file toast.sh file that contains the commands to run. The attacker also creates a folder named `. -exec bash toast.sh {} +` that will later become part of the shell `find` command forming `find . -exec bash toast.sh {} +`.
```

2024-11-07 10:55 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
> +Instead of listing files, the code in `noncompliant01.py` prints the first line of `/etc/passwd` on Linux or starts `net user` under Windows.
This seems to behave differently for me in Windows... we should discuss

2024-11-07 11:00 UTC, BartyBoi1128 commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
> +The `noncompliant02.py` example demonstrates the injection via file or folder name that is created prior to using the `list_dir()` method. We assume here that an untrusted user is allowed to create f
Maybe there should be a link to this?

2024-11-07 13:42 UTC, myteron commented on docs/Secure-Coding-Guide-for-Python/CWE-707/CWE-78/README.md
> +The `noncompliant02.py` example demonstrates the injection via file or folder name that is created prior to using the `list_dir()` method. We assume here that an untrusted user is allowed to create f
As discussed, links will come once those risks have a readme

2024-11-07 22:09 UTC, gkunz approved these changes
I cannot test the Windows runtime behavior issue @BartyBoi1128 pointed out, but I am ok with the other changes.

2024-11-08 13:32 UTC, BartyBoi1128 approved these changes

2024-11-08 13:49 UTC, myteron commented
Got approval from Bart.

This is part of #531

2024-11-08 13:50 UTC, merged